# Azure China container registries are *.azurecr.cn.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontobricks
spec:
  template:
    spec:
      containers:
        - name: ontobricks
          image: ontobrickscn.azurecr.cn/ontobricks:dbaeafcb
